--USUWANIE WSZYSTKICH REKORDOW JEŒLI CHCEMY ODZYSKAC STRUKTURE BAZY
DROP TABLE ORDER_DETAILS;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE EMPLOYEES;
DROP TABLE CUSTOMERS;
DROP TABLE TAX;
DROP TABLE JOBS;
DROP TABLE DISCOUNTS;
DROP TABLE BUILDINGS;
DROP TABLE ADDRESSES;
DROP VIEW PRODUKTY;
DROP VIEW CUSTOMERS_VIEW;
DROP VIEW FAKTURA;
DROP TABLE PRODUCTS_LOG;
DROP TABLE CUSTOMER_LOG;

-- TABELA: ADDRESSES
CREATE TABLE ADDRESSES
(ADDRESS_ID NUMBER (4, 0) PRIMARY KEY,
ADDRESS VARCHAR2 (100) NOT NULL);

-- TABELA: BUILDINGS
CREATE TABLE BUILDINGS 
(BUILDING_ID NUMBER (3, 0) PRIMARY KEY,
BUILDING_NAME VARCHAR2 (20) NOT NULL, 
ADDRESS_ID NUMBER (4, 0) REFERENCES ADDRESSES (ADDRESS_ID));

-- TABELA: DISCOUNTS
CREATE TABLE DISCOUNTS
(DISCOUNT_ID NUMBER (2, 0) PRIMARY KEY,
DISCOUNT_VALUE NUMBER (2, 1) NOT NULL UNIQUE);

-- TABELA: JOBS
CREATE TABLE JOBS
(JOB_ID NUMBER (2, 0) PRIMARY KEY,
JOB_TITLE VARCHAR2 (20) NOT NULL,
EMPLOYMENT_FORM NUMBER (2,1) NOT NULL);

-- TABELA: TAX
CREATE TABLE TAX
(TAX_ID NUMBER (1, 0) PRIMARY KEY,
TAX_VALUE REAL,
TAX_DESCRIPTION VARCHAR2 (100));

-- TABELA: CUSTOMERS
CREATE TABLE CUSTOMERS 
(CUSTOMER_ID NUMBER (3, 0) PRIMARY KEY,
FIRST_NAME VARCHAR2 (16) NOT NULL,
LAST_NAME VARCHAR2 (30) NOT NULL,
COMPANY_NAME VARCHAR2 (30),
PHONE_NUMBER NUMBER (9, 0) NOT NULL UNIQUE,
E_MAIL VARCHAR2 (30) UNIQUE NOT NULL, 
ADDRESS_ID NUMBER (3, 0) REFERENCES ADDRESSES (ADDRESS_ID) NOT NULL,
DISCOUNT_ID NUMBER (2, 0) REFERENCES DISCOUNTS (DISCOUNT_ID) NOT NULL);

-- TABELA: EMPLOYEES
CREATE TABLE EMPLOYEES (EMPLOYEE_ID NUMBER (4, 0) PRIMARY KEY, 
FIRST_NAME VARCHAR2 (16) NOT NULL, 
LAST_NAME VARCHAR2 (30) NOT NULL, 
SALARY NUMBER (6, 0) NOT NULL, DATE_OF_BIRTH DATE NOT NULL, 
HIRE_DATE DATE NOT NULL,
BUILDING_ID NUMBER (4, 0) REFERENCES BUILDINGS (BUILDING_ID) NOT NULL,
JOB_ID NUMBER (2, 0) REFERENCES JOBS (JOB_ID));

-- TABELA: PRODUCTS
CREATE TABLE PRODUCTS 
(PRODUCT_ID NUMBER (6, 0) PRIMARY KEY,
PRODUCT_NAME VARCHAR2 (30) NOT NULL UNIQUE,
PRICE_NET REAL NOT NULL, 
TAX_ID NUMBER (2, 0) REFERENCES TAX (TAX_ID) NOT NULL,
AVAILABILITY NUMBER (6, 0) NOT NULL,
BUILDING_ID NUMBER (2, 0) REFERENCES BUILDINGS (BUILDING_ID) NOT NULL);




-- TABELA: ORDERS
CREATE TABLE ORDERS 
(ORDER_ID NUMBER (6, 0) PRIMARY KEY, 
CUSTOMER_ID NUMBER (3, 0) REFERENCES CUSTOMERS (CUSTOMER_ID),
EMPLOYEE_ID NUMBER (4, 0) REFERENCES EMPLOYEES (EMPLOYEE_ID) NOT NULL,
STATUS VARCHAR2 (16) NOT NULL CHECK (STATUS IN('PREPARATION','WAY' ,'DELIVERED', 'MISSING')),
ORDER_DATE DATE NOT NULL, COMMENTS VARCHAR2 (100));

-- TABELA: ORDER_DETAILS
CREATE TABLE ORDER_DETAILS
(ORDER_ID NUMBER (6, 0) REFERENCES ORDERS (ORDER_ID),
PRODUCT_ID NUMBER (6, 0) REFERENCES PRODUCTS,
PRODUCT_AMMOUNT NUMBER (6, 0) NOT NULL, PRIMARY KEY (ORDER_ID, PRODUCT_ID));

--TWORZENIE WIDOKU PRODUKTY
CREATE VIEW PRODUKTY AS
    SELECT
    S.PRODUCT_ID AS "ID PRODUKTU",
    S.PRODUCT_NAME AS "NAZWA PRODUKTU",
    S.PRICE_NET "CENA NETTO",
    (S.PRICE_NET*T.TAX_VALUE+S.PRICE_NET) AS "CENA BRUTTO",
    S.AVAILABILITY AS "ILOSC SZTUK",
    B.BUILDING_NAME AS "NAZWA BUDYNKU",
    A.ADDRESS AS "ADRES"
    FROM PRODUCTS S
    JOIN TAX T
    ON  S.TAX_ID=T.TAX_ID
    JOIN BUILDINGS B
    ON S.BUILDING_ID=B.BUILDING_ID
    JOIN ADDRESSES A
    ON B.ADDRESS_ID=A.ADDRESS_ID;

--TWORZENIE WIDOKU CUSTOMERS_VIEW
CREATE VIEW CUSTOMERS_VIEW AS
    SELECT CU.CUSTOMER_ID, CU.FIRST_NAME, CU.LAST_NAME, 
    CU.COMPANY_NAME, CU.PHONE_NUMBER, CU.E_MAIL, AD.ADDRESS, D.DISCOUNT_VALUE
    FROM CUSTOMERS CU 
   JOIN ADDRESSES AD ON CU.ADDRESS_ID = AD.ADDRESS_ID
   JOIN DISCOUNTS D ON CU.DISCOUNT_ID = D.DISCOUNT_ID;

--TWORZENIE WIDOKU FAKTURA
CREATE VIEW FAKTURA AS
SELECT OD.ORDER_ID AS "NUMER ZAMOWIENIA",
CONCAT(CONCAT(C.FIRST_NAME,' '), C.LAST_NAME) AS "IMIE I NAZWISKO ZAMAWIAJACEGO",
C.COMPANY_NAME AS "FIRMA",
A.ADDRESS AS "ADRES ZAMAWIAJACEGO", O.ORDER_DATE AS "DATA ZAMOWIENIA",
CONCAT(CONCAT(E.FIRST_NAME,' '), E.LAST_NAME) AS "ZAMOWIENIE PRZYJAL/ELA",
P.PRODUCT_NAME AS "NAZWA PRODUKTU",
PRODUCT_AMMOUNT AS "ILOSC PRODUKTU",
PRICE_NET AS "CENA ZA SZTUKE",
(PRODUCT_AMMOUNT * PRICE_NET) AS "CENA NETTO ZAMOWIENIA",
(PRODUCT_AMMOUNT*(P.PRICE_NET*T.TAX_VALUE +P.PRICE_NET)) AS "CENA BRUTTO ZAMOWIENIA",
T.TAX_VALUE AS "PODATEK VAT",
O.COMMENTS AS "KOMENTARZE"
FROM ORDER_DETAILS OD
JOIN ORDERS O
ON OD.ORDER_ID=O.ORDER_ID
JOIN CUSTOMERS C
ON O.CUSTOMER_ID=C.CUSTOMER_ID
JOIN ADDRESSES A
ON C.ADDRESS_ID=A.ADDRESS_ID
JOIN EMPLOYEES E
ON O.EMPLOYEE_ID=E.EMPLOYEE_ID
JOIN PRODUCTS P
ON OD.PRODUCT_ID=P.PRODUCT_ID
JOIN TAX T
ON P.TAX_ID=T.TAX_ID
ORDER BY OD.ORDER_ID ASC;

--LOG PRZECHOWUAJCY ZMIANY W TABELI CUSTOMERS
CREATE TABLE CUSTOMER_LOG (
    "OLD_CUSTOMER_ID" NUMBER(6,0),
    "NEW_CUSTOMER_ID" NUMBER(6,0),
    "OLD_FIRST_NAME" VARCHAR2(16),
    "NEW_FIRST_NAME" VARCHAR2(16),
    "OLD_LAST_NAME" VARCHAR2(30),
    "NEW_LAST_NAME" VARCHAR2(30),
    "OLD_COMPANY_NAME" VARCHAR2(30),
    "NEW_COMPANY_NAME" VARCHAR2(30),
    "OLD_PHONE_NUMBER" NUMBER(9),
    "NEW_PHONE_NUMBER" NUMBER(9),
    "OLD_E_MAIL" VARCHAR2(30),
    "NEW_E_MAIL" VARCHAR2(30),
    "OLD_ADDRESS_ID" NUMBER(4),
    "NEW_ADDRESS_ID" NUMBER(4),
    "OLD_DISCOUNT_ID" NUMBER(2),
    "NEW_DISCOUNT_ID" NUMBER(2),
    "UPDATED_ON" DATE
);

--TRIGGER DO OBSLUGI LOGA KLIENTOW
CREATE OR REPLACE TRIGGER CUSTOMER_TRIGGER
BEFORE UPDATE OR INSERT OR DELETE ON CUSTOMERS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
IF UPDATING THEN
INSERT INTO CUSTOMER_LOG VALUES
(:OLD.CUSTOMER_ID,:NEW.CUSTOMER_ID, :OLD.FIRST_NAME,:NEW.FIRST_NAME, :OLD.LAST_NAME,:NEW.LAST_NAME, :OLD.COMPANY_NAME,:NEW.COMPANY_NAME,
:OLD.PHONE_NUMBER,:NEW.PHONE_NUMBER, :OLD.E_MAIL, :NEW.E_MAIL,  :OLD.ADDRESS_ID,:NEW.ADDRESS_ID,:OLD.DISCOUNT_ID,:NEW.DISCOUNT_ID,
SYSDATE);
END IF;
IF INSERTING THEN
INSERT INTO CUSTOMER_LOG VALUES
(:OLD.CUSTOMER_ID,:NEW.CUSTOMER_ID, :OLD.FIRST_NAME,:NEW.FIRST_NAME, :OLD.LAST_NAME,:NEW.LAST_NAME, :OLD.COMPANY_NAME,:NEW.COMPANY_NAME,
:OLD.PHONE_NUMBER,:NEW.PHONE_NUMBER, :OLD.E_MAIL, :NEW.E_MAIL,  :OLD.ADDRESS_ID,:NEW.ADDRESS_ID,:OLD.DISCOUNT_ID,:NEW.DISCOUNT_ID,
SYSDATE);
END IF;
IF DELETING THEN
INSERT INTO CUSTOMER_LOG VALUES
(:OLD.CUSTOMER_ID,:NEW.CUSTOMER_ID, :OLD.FIRST_NAME,:NEW.FIRST_NAME, :OLD.LAST_NAME,:NEW.LAST_NAME, :OLD.COMPANY_NAME,:NEW.COMPANY_NAME,
:OLD.PHONE_NUMBER,:NEW.PHONE_NUMBER, :OLD.E_MAIL, :NEW.E_MAIL,  :OLD.ADDRESS_ID,:NEW.ADDRESS_ID,:OLD.DISCOUNT_ID,:NEW.DISCOUNT_ID,
SYSDATE);
END IF;
END;
/

--LOG PRZECHOWUAJCY ZMIANY W TABELI PRODUCTS
CREATE TABLE PRODUCTS_LOG(
"OLD_PRODUCT_ID" NUMBER(6,0),
"NEW_PRODUCT_ID" NUMBER(6,0),
"OLD_PRODUCT_NAME" VARCHAR2(30),
"NEW_PRODUCT_NAME" VARCHAR2(30),
"OLD_PRICE_NET" NUMBER(6,0),
"NEW_PRICE_NET" NUMBER(6,0),
"OLD_TAX_ID" NUMBER(2,0),
"NEW_TAX_ID" NUMBER(2,0),
"OLD_AVAILABILITY" NUMBER(6,0),
"NEW_AVAILABILITY" NUMBER(6,0),
"OLD_BUILDING_ID" NUMBER (3,0),
"NEW_BUILDING_ID" NUMBER (3,0),
"UPDATED_ON" DATE
);

--TRIGGER DO OBSLUGI LOGA PRODUKTOW
CREATE OR REPLACE TRIGGER PRODUCTS_TRIGGER
BEFORE UPDATE OR INSERT OR DELETE ON PRODUCTS
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
IF UPDATING THEN
INSERT INTO PRODUCTS_LOG VALUES
(:OLD.PRODUCT_ID,:NEW.PRODUCT_ID, :OLD.PRODUCT_NAME,:NEW.PRODUCT_NAME, :OLD.PRICE_NET,:NEW.PRICE_NET, :OLD.TAX_ID,:NEW.TAX_ID,
:OLD.AVAILABILITY,:NEW.AVAILABILITY, :OLD.BUILDING_ID, :NEW.BUILDING_ID,SYSDATE);
END IF;
IF INSERTING THEN
INSERT INTO PRODUCTS_LOG VALUES
(:OLD.PRODUCT_ID,:NEW.PRODUCT_ID, :OLD.PRODUCT_NAME,:NEW.PRODUCT_NAME, :OLD.PRICE_NET,:NEW.PRICE_NET, :OLD.TAX_ID,:NEW.TAX_ID,
:OLD.AVAILABILITY,:NEW.AVAILABILITY, :OLD.BUILDING_ID, :NEW.BUILDING_ID,SYSDATE);
END IF;
IF DELETING THEN
INSERT INTO PRODUCTS_LOG VALUES
(:OLD.PRODUCT_ID,:NEW.PRODUCT_ID, :OLD.PRODUCT_NAME,:NEW.PRODUCT_NAME, :OLD.PRICE_NET,:NEW.PRICE_NET, :OLD.TAX_ID,:NEW.TAX_ID,
:OLD.AVAILABILITY,:NEW.AVAILABILITY, :OLD.BUILDING_ID, :NEW.BUILDING_ID,SYSDATE);
END IF;
END;
/



--DANE DO WYPELNIENIA BAZY DANYCH
--ADRESY
INSERT ALL
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('1','KRASICKIEGO 12, WROCLAW')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('2','WYSPIANSKIEGO 9, WROCLAW')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('3','RUSKA 15, WROCLAW')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('4','CZYSTA 8, LODZ')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('5','PIOTRKOWSKA 24, LODZ')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('6','SPORTOWA 1, KLESZCZOW')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('7','GALLA ANONIMA 5, GDANSK')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('8','KOLOROWA 2, POZNAN')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('9','MALA 1, WARSZAWA')
INTO ADDRESSES (ADDRESS_ID, ADDRESS)
VALUES ('10','SMOCZA 76, KRAKOW')
SELECT * FROM DUAL;

--BUDYNKI PRACOWNICZE
INSERT ALL
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('1','T1','1')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('2','T2','1')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('3','T3','2')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('4','G1','2')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('5','G2','2')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('6','G3','2')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('7','OF_1','2')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('8','OF_1','3')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('9','OF_2','3')
INTO BUILDINGS (BUILDING_ID, BUILDING_NAME, ADDRESS_ID)
VALUES('10','OF_2','3')
SELECT * FROM DUAL;

--ZNIZKI
INSERT ALL
INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_VALUE)
VALUES ('1', 0.1)
INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_VALUE)
VALUES ('2', 0.2)
INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_VALUE)
VALUES ('3', 0.3)
INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_VALUE)
VALUES ('4', 0.5)
INTO DISCOUNTS(DISCOUNT_ID, DISCOUNT_VALUE)
VALUES ('5', 0.8)
SELECT * FROM DUAL;

--STANOWISKA
INSERT ALL
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('1','BLUE COLLAR', 0.5)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('2','BLUE COLLAR', 1)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('3','SELLER', 1)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('4','SECRETARY', 0.5)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('5','ENGINEER', 0.5)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('6','CHARWOMAN', 1)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('7','TEMPORARY WORKER', 0.5)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('8','ACCOUNTANT', 1)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('9','MANAGER', 0.5)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('10','MANAGER', 1)
INTO JOBS (JOB_ID, JOB_TITLE, EMPLOYMENT_FORM)
VALUES ('11','FORK LIFT DRIVER', 1)
SELECT * FROM DUAL;

--RODZAJE PODATKOW
INSERT ALL
INTO TAX(TAX_ID, TAX_VALUE, TAX_DESCRIPTION)
VALUES('1', 0, 'Nieopodatkowane')
INTO TAX(TAX_ID, TAX_VALUE, TAX_DESCRIPTION)
VALUES('2', 0.23, 'Podatek podstawowy')
INTO TAX(TAX_ID, TAX_VALUE, TAX_DESCRIPTION)
VALUES('3', 0.08, 'Podatek obnizony')
INTO TAX(TAX_ID, TAX_VALUE, TAX_DESCRIPTION)
VALUES('4', 0.05, 'Podatek obnizony')
SELECT * FROM DUAL;
--PRODUKTY
INSERT ALL
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('1','CHLEB PSZENNY DOMOWY',2.5, 2,1000, 1)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('2','CHLEB RAZOWY BEDNAREK',3, 2,2445, 2)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('3','DELMA',5, 2,4545, 3)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('4','LAYS',2.8, 2,11234, 2)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('5','SZYNKA Z LISCIEM',13, 2,1929, 1)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('6','KARKOWKA DOMOWA',12, 3,23256, 2)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('7','SZYNKA ZBOJECKA',10, 2,3456, 3)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('8','KIELBASA PODWAWELSKA',15, 2,3452, 1)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('9','ZELKI HARIBO',3, 2,3425, 2)
INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID, AVAILABILITY, BUILDING_ID)
VALUES('10','SOK TYMBARK',2, 3,75432, 1)
SELECT * FROM DUAL;

--PRACOWNICY
INSERT ALL
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('1','ANNA','KRAWCZYK',2500,'1977-11-11','2017-10-23',1,1)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('2','MARTA','GLOWACKA',2400,'1987-11-06','2011-05-06',1,2)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('3','KASIA','IWANOWA',5000,'1999-10-23','2014-07-12',2,3)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('4','JULIA','BASARA',3000,'1945-06-07','2012-10-21',3,4)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('5','AGNIESZKA','POLANSKA',6000,'1968-05-23','2017-06-07',4,5)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('6','MARCIN','KUBELEK',2500,'1975-07-07','2011-10-12',5,6)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('7','ADRIAN','PROSTY',1500,'2001-10-05','2014-06-07',6,7)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('8','KUBA','PIEKARCZYK',4000,'1960-10-07','2015-06-03',7,8)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('9','KAMIL','BEDNAREK',10000,'1987-06-05','2015-04-06',8,9)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('10','KAZIMIERZ','WIELKI',20000,'1999-06-15','2013-05-02',9,10)
INTO EMPLOYEES(EMPLOYEE_ID, FIRST_NAME,LAST_NAME,SALARY,DATE_OF_BIRTH,HIRE_DATE,BUILDING_ID,JOB_ID)
VALUES('11','MAREK','KIERUJACY',3000,'1990-10-12','2014-02-05',1,11)
SELECT * FROM DUAL;

--KLIENCI
INSERT ALL
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('1','ALICJA','KOLOWSKA','ZABKA','324234543','ALICJA@GMAIL.COM',4,1)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('2','ADRIANNA','RZECHOWICZ','FRESH','458733542','ADRIANNA@GMAIL.COM',5,2)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('3','BEATA','NIEDBALEC','TESCO','643734572','BEATA@GMAIL.COM',6,3)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('4','FELICJA','BIELAWA','LIDL','346523461','FELICJA@GMAIL.COM',7,4)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('5','WANDA','STACHLEWSKI','KAUFLAND','237345262','WANDA@GMAIL.COM',8,5)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('6','ABRAHAM','BASARA','ALDI','334627345','ABRAHAM@GMAIL.COM',9,1)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('7','FABIAN','FABECKI','DELIKATESY','135634257','FABIAN@GMAIL.COM',10,2)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('8','IGNACY','WABERZAK','734252314','IGNACY@GMAIL.COM',5,3)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('9','WLADYSLAW','WABICZ','194239458','WLADYSLAW@GMAIL.COM',6,4)
INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('10','ZBIGNIEW','SABCZYNSKI','997112998','ZBIGNIEW@GMAIL.COM',7,5)
SELECT * FROM DUAL;

--ZAMOWIENIA
INSERT ALL 
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('1','1','1','PREPARATION','2018-05-05','DOKLADNIEJ ZAPAKOWAC')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('2','2','1','PREPARATION','2018-05-08','DOKLADNIEJ ZAPAKOWAC')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('3','3','1','WAY','2018-03-09','UWAGA TOWAR MIEKKI')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('4','4','2','WAY','2018-02-12','UWAGA TOWAR MIEKKI')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('5','5','2','WAY','2018-02-13','UZYWAC REKAWICZEK')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('6','6','2','DELIVERED','2018-03-14','UZYWAC REKAWICZEK')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('7','7','3','DELIVERED','2018-03-15','PAKOWAC PO 200')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('8','8','3','DELIVERED','2018-04-16','PAKOWAC PO 15')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE,COMMENTS)
VALUES ('9','9','4','MISSING','2018-02-16','PAKOWAC PO 250')
INTO ORDERS(ORDER_ID,CUSTOMER_ID,EMPLOYEE_ID,STATUS,ORDER_DATE)
VALUES ('10','10','4','MISSING','2018-03-05')
SELECT * FROM DUAL;

--ZAMOWIENIA Z PRODUKTEM I ILOSCIA(Z KLUCZAMI KOMPOZYTOWYMI)
INSERT ALL
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(1,1,2500)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(1,2,3000)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(1,3,1500)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(1,4,200)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(2,5,600)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(2,6,700)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(2,7,400)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(2,8,500)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(2,9,800)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(3,10,1000)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(4,1,100)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(5,2,250)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(6,3,340)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(7,4,380)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(8,5,520)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(9,5,420)
INTO ORDER_DETAILS(ORDER_ID,PRODUCT_ID,PRODUCT_AMMOUNT)
VALUES(10,5,120)
SELECT * FROM DUAL;

-- PRZYKALDOWE INSERTY I DELETE DO POKAZANIA DZIALANIA TRIGGEROW I LOGOW
INSERT INTO CUSTOMERS(CUSTOMER_ID,FIRST_NAME,LAST_NAME,COMPANY_NAME,PHONE_NUMBER,E_MAIL,ADDRESS_ID,DISCOUNT_ID)
VALUES('11','MARIAN','PAZDIOCH','ZABKA','234432575','MARIANEK@GMAIL.COM',4,1);

UPDATE CUSTOMERS SET 
CUSTOMER_ID = 12, FIRST_NAME = 'MARCIN', LAST_NAME = 'KOWALSKI', COMPANY_NAME = 'LIDL', PHONE_NUMBER= 123456789,
E_MAIL ='NOWYMAIL@GMAIL.COM', ADDRESS_ID = 5, DISCOUNT_ID = 2 WHERE CUSTOMER_ID=11;

DELETE FROM CUSTOMERS
WHERE CUSTOMER_ID=12;

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME,PRICE_NET,TAX_ID,AVAILABILITY,BUILDING_ID)
VALUES (11,'WODA MINERALNA',2,2,100,2);

UPDATE PRODUCTS SET 
PRODUCT_ID= 12, PRODUCT_NAME= 'WODA ZRODLANA', PRICE_NET = 2.5, TAX_ID = 3, AVAILABILITY = 150, BUILDING_ID = 3
WHERE PRODUCT_ID=11;

DELETE FROM PRODUCTS
WHERE PRODUCT_ID=12;

